# Generated by ./update.sh - do not update manually!
{
  version = "0.35.3";

  platformList = [
    "aarch64-linux"
    "x86_64-linux"
    "x86_64-darwin"
    "aarch64-darwin"
  ];

  archMap = {
    aarch64-linux = "linux_arm64";
    x86_64-linux = "linux_amd64";
    x86_64-darwin = "darwin_amd64";
    aarch64-darwin = "darwin_arm64";
  };

  fetchurlAttrSet = {

    aarch64-linux.docker-credential-up = {
      hash = "sha256-629J54qXePNTs12R/Tn5g6h1WDMoCfpdi+pfxPKFtAc=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/docker-credential-up/linux_arm64.tar.gz";
    };
    x86_64-linux.docker-credential-up = {
      hash = "sha256-2bfryUBfWC/jaX/eL9+X2XcDFXBi90k+MlKSsCmZ7K0=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/docker-credential-up/linux_amd64.tar.gz";
    };
    x86_64-darwin.docker-credential-up = {
      hash = "sha256-YXs6EBDkqaSB7eKmghxRTwtmJzlEBEtiKDJpRijeLEU=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/docker-credential-up/darwin_amd64.tar.gz";
    };
    aarch64-darwin.docker-credential-up = {
      hash = "sha256-ePAdir+J/weqcxbcdxqp1Z3XxppKef/uiQIWgnNcle4=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/docker-credential-up/darwin_arm64.tar.gz";
    };
    aarch64-linux.up = {
      hash = "sha256-aQ+0/jPMONAQxnHwdvArMALw+tUcEEvxAdEEpCywVaM=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/up/linux_arm64.tar.gz";
    };
    x86_64-linux.up = {
      hash = "sha256-TZylxlgXZCr1v5dQndRrxZ3o0Y1WCLaKi+OsNLUZtT8=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/up/linux_amd64.tar.gz";
    };
    x86_64-darwin.up = {
      hash = "sha256-34mGA400VREXCr6IBc9sa/MI46SV0xqZSyr1z7HcMMY=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/up/darwin_amd64.tar.gz";
    };
    aarch64-darwin.up = {
      hash = "sha256-jvvhhZNe8GATeMr44gVqqBbcQbSQJdWd4x1TzUSJCR0=";
      url = "https://cli.upbound.io/stable/v0.35.3/bundle/up/darwin_arm64.tar.gz";
    };
  };
}
