#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl

#set -euo pipefail
currentVersion=$(curl https://cli.upbound.io/stable/current/version)
version="${currentVersion:1}"

declare -A archMapping
archMapping["aarch64-darwin"]="darwin_arm64"
archMapping["x86_64-darwin"]="darwin_amd64"
archMapping["aarch64-linux"]="linux_arm64"
archMapping["x86_64-linux"]="linux_amd64"

archMapBlock=
for key in "${!archMapping[@]}"; do
    line=$(printf "$key = \"${archMapping[$key]}\"; ")
    archMapBlock="$archMapBlock$line"
done

platformListBlock=
for key in "${!archMapping[@]}"; do
    platformListBlock="$platformListBlock\"$key\" "
done

cmds=("docker-credential-up" "up")
fetchurlAttrSetBlock=
for cmd in "${cmds[@]}"; do
    for key in "${!archMapping[@]}"; do
        arch=${archMapping[$key]}
        url="https://cli.upbound.io/stable/v${version}/bundle/$cmd/${arch}.tar.gz";
        hash=$(nix-prefetch-url $url)
        hash=$(nix hash convert "${hash}" --hash-algo sha256)
        fetchurlAttrSetBlock="
        ${fetchurlAttrSetBlock}
        $key.$cmd = {
          hash = \"${hash}\";
          url = ${url};
        };"
    done
done

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
{
  version = "${version}";

  platformList = [
    ${platformListBlock}
    ];

  archMap = {
    ${archMapBlock}
    };

  fetchurlAttrSet = {
    ${fetchurlAttrSetBlock}
    };
}
EOF

nixfmt sources.nix
